#!/usr/bin/env python3
"""
E_accumulated_reward.py

Comprehensive reward analysis and visualization tool for MARL training.

This script:
1. Validates episode rewards correctness (cross-checks with individual episode CSVs)
2. Loads episode rewards from episode_rewards.csv (generated by training)
3. Computes cumulative rewards across episodes (for trend analysis)
4. Generates multiple visualizations:
   - Episode rewards (per episode, NOT cumulative)
   - Moving average for smoothed trends
   - Cumulative rewards (running sum for overall learning trend)
5. Saves results to Excel and SVG plots

IMPORTANT NOTES:
- Uses episode_rewards.csv as the source of truth
- Each episode reward = sum of timestep rewards WITHIN that episode
- Episode rewards reset each episode (NOT cumulative)
- Cumulative plot shows running sum ACROSS episodes (for trend visualization only)
- Includes validation checks to ensure data integrity

Output:
- Excel: agent_rewards_cumulative.xlsx (Episode_Rewards, Cumulative_Sum, Statistics)
- SVG: episode_rewards.svg (per episode rewards)
- SVG: episode_rewards_moving_avg.svg (smoothed trend)
- SVG: cumulative_rewards.svg (cumulative trend visualization)
"""

import pandas as pd
import os
import glob
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from pathlib import Path
import sys

# Add project root to path for imports
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from configs.loader import load_config


# --- PLOT CONFIGURATION ---
# Control which plots to generate and which agents to display in each plot
PLOT_CONFIG = {
    'episode_rewards': {
        'enabled': True,
        'agents': None  # None = all agents  'battery#0', 'grid#0', 'load#0', 'solar#0', 'wind#0'
    },
    'episode_rewards_moving_avg': {
        'enabled': True,
        'agents': None  # None = all agents
    },
    'cumulative_rewards': {
        'enabled': True,
        'agents': None  # None = all agents
    }
}

# Examples of customization:
# - To show only battery and grid in cumulative plot:
#   PLOT_CONFIG['cumulative_rewards']['agents'] = ['battery#0', 'grid#0']
# - To show all available agents, set to None:
#   PLOT_CONFIG['episode_rewards']['agents'] = None
# - To disable a plot entirely:
#   PLOT_CONFIG['episode_rewards']['enabled'] = False


def load_episode_rewards(rewards_file: str = "results/logs/episode_rewards.csv"):
    """
    Load episode rewards from CSV file with validation.
    
    Args:
        rewards_file: Path to episode_rewards.csv
        
    Returns:
        DataFrame with episode rewards, or None if file not found/invalid
    """
    if not os.path.exists(rewards_file):
        print(f"❌ Episode rewards file not found: {rewards_file}")
        print("Please run training first to generate episode_rewards.csv")
        return None
    
    df = pd.read_csv(rewards_file)
    print(f"✅ Loaded episode rewards: {len(df)} episodes")
    
    # Validate structure
    if 'episode' not in df.columns:
        print("❌ ERROR: Missing 'episode' column in CSV")
        return None
    
    # Validate episode numbering
    expected_episodes = set(range(len(df)))
    actual_episodes = set(df['episode'].values)
    
    if expected_episodes != actual_episodes:
        print("❌ ERROR: Episode numbering mismatch")
        print(f"   Expected: 0 to {len(df) - 1}")
        print(f"   Found issues in numbering")
        return None
    
    # Get agent columns
    agent_columns = [col for col in df.columns if col != 'episode']
    
    if not agent_columns:
        print("❌ ERROR: No agent columns found in CSV")
        return None
    
    print(f"📊 Found {len(agent_columns)} agents: {agent_columns}")
    print(f"✅ Episode numbering validated: 0 to {len(df) - 1}")
    
    return df


def verify_episode_rewards(df: pd.DataFrame, sample_size: int = 8, verbose: bool = True):
    """
    Verify episode rewards by cross-checking with individual episode CSVs.
    
    This validation ensures that:
    1. Episode rewards match manual sum from episode CSVs
    2. No accumulation across episodes has occurred
    3. Data structure is correct
    
    Args:
        df: DataFrame with episode rewards from CSV
        sample_size: Number of episodes to verify (first, last, middle, random)
        verbose: Whether to print detailed verification output
        
    Returns:
        Boolean indicating if verification passed
    """
    if verbose:
        print("\n" + "="*70)
        print("🔍 EPISODE REWARD VERIFICATION")
        print("="*70)
    
    evolution_dir = "results/evolution"
    if not os.path.exists(evolution_dir):
        if verbose:
            print(f"\n⚠️  Evolution directory not found: {evolution_dir}")
            print("Skipping detailed verification.")
        return True
    
    # Get episode files
    episode_files = sorted(glob.glob(f"{evolution_dir}/episode_*.csv"))
    num_files = len(episode_files)
    
    if num_files == 0:
        if verbose:
            print(f"\n⚠️  No episode files found in {evolution_dir}")
        return True
    
    if verbose:
        print(f"\n✅ Found {num_files} episode files")
    
    # Select sample episodes to verify
    sample_indices = [0]  # First episode
    if num_files > 1:
        sample_indices.append(num_files - 1)  # Last episode
    if num_files > 2:
        sample_indices.append(num_files // 2)  # Middle episode
    if num_files > 10:
        # Add random samples
        np.random.seed(42)
        extra_samples = np.random.choice(
            range(1, num_files - 1),
            size=min(sample_size - 3, num_files - 2),
            replace=False
        )
        sample_indices.extend(extra_samples)
    
    sample_indices = sorted(set(sample_indices))
    
    if verbose:
        print(f"🔍 Verifying {len(sample_indices)} sample episodes: {sample_indices}")
    
    agent_columns = [col for col in df.columns if col != 'episode']
    all_valid = True
    tolerance = 1e-6
    matches = 0
    total_checks = 0
    
    for ep_num in sample_indices:
        ep_file = f"{evolution_dir}/episode_{ep_num}.csv"
        
        if not os.path.exists(ep_file):
            if verbose:
                print(f"  ⚠️  Episode {ep_num}: File not found")
            continue
        
        # Load episode evolution data
        ep_df = pd.read_csv(ep_file)
        
        # Find reward columns
        reward_cols = [col for col in ep_df.columns if col.startswith('reward_')]
        
        if not reward_cols:
            if verbose:
                print(f"  ⚠️  Episode {ep_num}: No reward columns found")
            continue
        
        # Verify each agent
        for reward_col in reward_cols:
            agent_name = reward_col.replace('reward_', '')
            
            if agent_name not in agent_columns:
                continue
            
            # Calculate manual sum (excluding initial state at step -1 if present)
            episode_data = ep_df[ep_df['step'] >= 0]
            manual_sum = episode_data[reward_col].sum()
            
            # Get stored value
            stored_value = df.loc[df['episode'] == ep_num, agent_name].values
            
            if len(stored_value) == 0:
                if verbose:
                    print(f"  ❌ Episode {ep_num}, {agent_name}: Not found in CSV")
                all_valid = False
                continue
            
            stored_value = stored_value[0]
            diff = abs(manual_sum - stored_value)
            total_checks += 1
            
            if diff > tolerance:
                if verbose:
                    print(f"  ❌ Episode {ep_num}, {agent_name}: MISMATCH")
                    print(f"     Manual sum: {manual_sum:.6f}")
                    print(f"     Stored:     {stored_value:.6f}")
                    print(f"     Difference: {diff:.6f}")
                all_valid = False
            else:
                matches += 1
                if verbose:
                    print(f"  ✅ Episode {ep_num}, {agent_name}: Match ({stored_value:.3f})")
    
    # Print verification summary
    if verbose:
        print("\n" + "="*70)
        if all_valid:
            print("✅ VERIFICATION PASSED")
            print("="*70)
            print(f"\n✅ All {matches}/{total_checks} checked values match:")
            print("  - Episode rewards = sum of timestep rewards within episode")
            print("  - No accumulation across episodes detected")
            print("  - Data structure is correct")
        else:
            # Relaxed behaviour: warn but do NOT fail the pipeline.
            print("❌ VERIFICATION FAILED (warnings only)")
            print("="*70)
            print(f"\n❌ {matches}/{total_checks} checks passed")
            print("Some episodes have mismatched rewards; proceeding with analysis anyway.")
            print("If this is unexpected, please review core/simulation.py and the reward logging.")

    # Always return True so that downstream analysis continues even if
    # mismatches are detected. The printed warnings still highlight issues.
    return True


def check_for_accumulation_errors(df: pd.DataFrame, verbose: bool = True):
    """
    Check if rewards are incorrectly accumulating across episodes.
    
    This detects the common bug where episode rewards are summed across
    episodes instead of resetting each episode.
    
    Args:
        df: DataFrame with episode rewards
        verbose: Whether to print detailed output
        
    Returns:
        Boolean indicating if data looks correct (True = no accumulation detected)
    """
    if verbose:
        print("\n" + "="*70)
        print("🔍 CHECKING FOR INCORRECT ACCUMULATION")
        print("="*70)
    
    agent_columns = [col for col in df.columns if col != 'episode']
    all_correct = True
    
    for agent in agent_columns:
        values = df[agent].values
        
        # Check if strictly increasing (sign of accumulation bug)
        is_monotonic = all(values[i] <= values[i+1] for i in range(len(values)-1))
        
        if is_monotonic and len(values) > 5:
            if verbose:
                print(f"  ⚠️  {agent}: Values are monotonically increasing!")
                print(f"     This suggests rewards may be accumulating across episodes.")
            all_correct = False
        else:
            if verbose:
                print(f"  ✅ {agent}: Values fluctuate (correct behavior)")
    
    if verbose:
        print("="*70)
    
    return all_correct


def compute_cumulative_rewards(df: pd.DataFrame):
    """
    Compute cumulative sum of episode rewards across episodes.
    
    This is for VISUALIZATION purposes only to show learning trends.
    The original episode rewards are NOT cumulative themselves.
    
    Args:
        df: DataFrame with episode rewards
        
    Returns:
        DataFrame with cumulative sums
    """
    agent_columns = [col for col in df.columns if col != 'episode']
    
    # Compute cumulative sum
    df_cumulative = df[agent_columns].cumsum()
    df_cumulative.insert(0, 'episode', df['episode'])
    
    print("\n📈 First 5 episodes (cumulative sum):")
    print(df_cumulative.head())
    
    print("\n📈 Last 5 episodes (cumulative sum):")
    print(df_cumulative.tail())
    
    return df_cumulative


def compute_statistics(df: pd.DataFrame, df_cumulative: pd.DataFrame):
    """
    Compute statistical summary of rewards.
    
    Args:
        df: Original episode rewards
        df_cumulative: Cumulative rewards
        
    Returns:
        DataFrame with statistics
    """
    agent_columns = [col for col in df.columns if col != 'episode']
    
    stats = pd.DataFrame({
        'mean_per_episode': df[agent_columns].mean(),
        'std_per_episode': df[agent_columns].std(),
        'min_episode_reward': df[agent_columns].min(),
        'max_episode_reward': df[agent_columns].max(),
        'total_cumulative': df_cumulative[agent_columns].iloc[-1]
    }).round(3)
    
    print("\n📊 Statistics Summary:")
    print(stats.to_string())
    
    return stats


def save_to_excel(df: pd.DataFrame, df_cumulative: pd.DataFrame, 
                  stats: pd.DataFrame, output_path: str):
    """
    Save data to Excel file with multiple sheets.
    
    Args:
        df: Episode rewards
        df_cumulative: Cumulative rewards
        stats: Statistics
        output_path: Output Excel file path
    """
    try:
        with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
            df.to_excel(writer, sheet_name='Episode_Rewards', index=False)
            df_cumulative.to_excel(writer, sheet_name='Cumulative_Sum', index=False)
            stats.to_excel(writer, sheet_name='Statistics')
        print(f"\n✅ Excel file saved: {output_path}")
    except Exception as e:
        print(f"\n❌ Error saving Excel: {e}")


def plot_cumulative_rewards(df_cumulative: pd.DataFrame, output_dir: str):
    """
    Generate cumulative reward visualization.
    
    This plot shows the running sum of episode rewards across episodes.
    It helps visualize the overall learning trend.
    
    Args:
        df_cumulative: DataFrame with cumulative rewards
        output_dir: Directory to save plot
    """
    config = PLOT_CONFIG['cumulative_rewards']
    if not config['enabled']:
        print("ℹ️  Skipping cumulative_rewards plot (disabled in PLOT_CONFIG)")
        return
    
    os.makedirs(output_dir, exist_ok=True)
    
    # Configure matplotlib
    matplotlib.use('Agg')
    plt.style.use('seaborn-v0_8-paper')
    
    # Get all available agents
    all_agents = [col for col in df_cumulative.columns if col != 'episode']
    
    # Filter agents based on configuration
    if config['agents'] is None:
        agent_columns = all_agents
    else:
        agent_columns = [a for a in config['agents'] if a in all_agents]
        if not agent_columns:
            print(f"⚠️  No valid agents found for cumulative_rewards. Available: {all_agents}")
            return
    
    print(f"📊 Plotting cumulative_rewards with agents: {agent_columns}")
    
    # Get colors
    colormap = plt.get_cmap('tab10')
    colors = [colormap(i) for i in range(len(agent_columns))]
    
    # Create plot
    fig, ax = plt.subplots(figsize=(14, 8))
    
    for idx, agent in enumerate(agent_columns):
        ax.plot(df_cumulative['episode'], df_cumulative[agent],
                marker='o', markersize=3, linewidth=2,
                label=agent, color=colors[idx], alpha=0.8)
    
    ax.set_title('Cumulative Reward Across Episodes (Learning Trend)', 
                 fontsize=16, fontweight='bold')
    ax.set_xlabel('Episode', fontsize=13)
    ax.set_ylabel('Cumulative Reward (Running Sum)', fontsize=13)
    ax.legend(title='Agent', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=True)
    ax.grid(True, linestyle='--', alpha=0.5)
    
    # Add note about interpretation
    note = 'Note: This shows the running sum of episode rewards for trend analysis.\nEach episode reward is calculated independently (not cumulative).'
    fig.text(0.5, 0.01, note, ha='center', fontsize=9, style='italic', color='gray')
    
    fig.tight_layout(rect=[0, 0.03, 0.88, 1])
    
    # Save plot
    plot_path = os.path.join(output_dir, 'cumulative_rewards.svg')
    plt.savefig(plot_path, format='svg', dpi=300, bbox_inches='tight')
    print(f"✅ Plot saved: {plot_path}")
    plt.close()


def plot_episode_rewards(df: pd.DataFrame, output_dir: str, window_size: int = None):
    """
    Generate episode reward visualizations (per episode, NOT cumulative).
    
    Creates two plots:
    1. Raw episode rewards showing performance per episode
    2. Moving average for smoothed trend analysis
    
    Args:
        df: DataFrame with episode rewards
        output_dir: Directory to save plots
        window_size: Window size for moving average (default: from config or adaptive)
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Configure matplotlib
    matplotlib.use('Agg')
    plt.style.use('seaborn-v0_8-paper')
    
    # Get all available agents
    all_agents = [col for col in df.columns if col != 'episode']
    
    # ========================================
    # Plot 1: Episode Rewards (NOT cumulative)
    # ========================================
    config_ep = PLOT_CONFIG['episode_rewards']
    if config_ep['enabled']:
        # Filter agents for this plot
        if config_ep['agents'] is None:
            agent_columns = all_agents
        else:
            agent_columns = [a for a in config_ep['agents'] if a in all_agents]
            if not agent_columns:
                print(f"⚠️  No valid agents for episode_rewards. Available: {all_agents}")
                agent_columns = all_agents
        
        print(f"📊 Plotting episode_rewards with agents: {agent_columns}")
        
        # Get colors
        colormap = plt.get_cmap('tab10')
        colors = [colormap(i) for i in range(len(agent_columns))]
        
        fig, ax = plt.subplots(figsize=(14, 8))
        
        for idx, agent in enumerate(agent_columns):
            ax.plot(df['episode'], df[agent], 
                    marker='o', markersize=3, linewidth=1.5,
                    label=agent, color=colors[idx], alpha=0.8)
        
        ax.set_title('Episode Rewards (Per Episode)', fontsize=16, fontweight='bold')
        ax.set_xlabel('Episode', fontsize=13)
        ax.set_ylabel('Episode Reward', fontsize=13)
        ax.legend(title='Agent', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=True)
        ax.grid(True, linestyle='--', alpha=0.5)
        fig.tight_layout(rect=[0, 0, 0.88, 1])
        
        # Save plot
        plot_path = os.path.join(output_dir, 'episode_rewards.svg')
        plt.savefig(plot_path, format='svg', dpi=300, bbox_inches='tight')
        print(f"✅ Plot saved: {plot_path}")
        plt.close()
    else:
        print("ℹ️  Skipping episode_rewards plot (disabled in PLOT_CONFIG)")
    
    # ========================================
    # Plot 2: Moving Average (smoothed)
    # ========================================
    config_ma = PLOT_CONFIG['episode_rewards_moving_avg']
    # Use provided window_size or fall back to adaptive calculation
    if window_size is None:
        window_size = min(100, len(df) // 4)  # Adaptive fallback
    if window_size >= 2 and config_ma['enabled']:
        # Filter agents for moving average plot
        if config_ma['agents'] is None:
            agent_columns = all_agents
        else:
            agent_columns = [a for a in config_ma['agents'] if a in all_agents]
            if not agent_columns:
                print(f"⚠️  No valid agents for moving_avg. Available: {all_agents}")
                agent_columns = all_agents
        
        print(f"📊 Plotting episode_rewards_moving_avg with agents: {agent_columns}")
        
        # Get colors
        colormap = plt.get_cmap('tab10')
        colors = [colormap(i) for i in range(len(agent_columns))]
        
        fig, ax = plt.subplots(figsize=(14, 8))
        
        for idx, agent in enumerate(agent_columns):
            moving_avg = df[agent].rolling(window=window_size, min_periods=1).mean()
            ax.plot(df['episode'], moving_avg,
                    linewidth=2.5, label=agent, color=colors[idx], alpha=0.9)
        
        ax.set_title(f'Episode Rewards (Moving Average, window={window_size})', 
                     fontsize=16, fontweight='bold')
        ax.set_xlabel('Episode', fontsize=13)
        ax.set_ylabel('Moving Average Reward', fontsize=13)
        ax.legend(title='Agent', bbox_to_anchor=(1.02, 1), loc='upper left', frameon=True)
        ax.grid(True, linestyle='--', alpha=0.5)
        fig.tight_layout(rect=[0, 0, 0.88, 1])
        
        # Save plot
        plot_path = os.path.join(output_dir, 'episode_rewards_moving_avg.svg')
        plt.savefig(plot_path, format='svg', dpi=300, bbox_inches='tight')
        print(f"✅ Plot saved: {plot_path}")
        plt.close()
    elif not config_ma['enabled']:
        print("ℹ️  Skipping episode_rewards_moving_avg plot (disabled in PLOT_CONFIG)")
    elif window_size < 2:
        print("ℹ️  Skipping moving average plot (insufficient data points)")



def analyze_learning_progress(df: pd.DataFrame):
    """
    Analyze learning progress by comparing early vs late episodes.
    
    Args:
        df: DataFrame with episode rewards
    """
    agent_columns = [col for col in df.columns if col != 'episode']
    
    n_episodes = len(df)
    n_compare = max(1, n_episodes // 10)
    
    first_episodes = df.head(n_compare)[agent_columns].mean()
    last_episodes = df.tail(n_compare)[agent_columns].mean()
    improvement = last_episodes - first_episodes
    improvement_pct = (improvement / first_episodes.abs()) * 100
    
    print("\n" + "="*70)
    print("📈 LEARNING PROGRESS ANALYSIS")
    print("="*70)
    
    comparison = pd.DataFrame({
        'First Episodes (avg)': first_episodes,
        'Last Episodes (avg)': last_episodes,
        'Improvement': improvement,
        'Improvement %': improvement_pct
    })
    
    print(f"\nComparing first {n_compare} vs last {n_compare} episodes:")
    print(comparison.to_string())


def main():
    """Main execution function."""
    print("="*80)
    print("📊 E_accumulated_reward.py - Cumulative Reward Analysis & Validation")
    print("="*80)
    
    # Load configuration
    config = load_config()
    window_size = config.get('stability', {}).get('window', 100)
    print(f"\n📋 Configuration loaded:")
    print(f"   - Moving average window size: {window_size}")
    
    # 1. Load episode rewards
    rewards_file = "results/logs/episode_rewards.csv"
    df = load_episode_rewards(rewards_file)
    
    if df is None:
        print("\n❌ Failed to load episode rewards. Exiting.")
        return False
    
    # 2. Verify episode rewards correctness
    verification_passed = verify_episode_rewards(df, sample_size=8, verbose=True)
    
    if not verification_passed:
        print("\n❌ Verification failed. Please check data integrity.")
        return False
    
    # 3. Check for accumulation errors
    no_accumulation = check_for_accumulation_errors(df, verbose=True)
    
    if not no_accumulation:
        print("\n⚠️  Warning: Potential accumulation issue detected.")
    
    # 4. Compute cumulative rewards
    df_cumulative = compute_cumulative_rewards(df)
    
    # 5. Compute statistics
    stats = compute_statistics(df, df_cumulative)
    
    # 6. Save to Excel
    output_dir = "results/plots"
    excel_output = os.path.join(output_dir, 'agent_rewards_cumulative.xlsx')
    save_to_excel(df, df_cumulative, stats, excel_output)
    
    # 7. Generate cumulative plot
    plot_cumulative_rewards(df_cumulative, output_dir)
    
    # 8. Generate episode reward plots (per episode)
    plot_episode_rewards(df, output_dir, window_size=window_size)
    
    # 9. Analyze learning progress
    analyze_learning_progress(df)
    
    print("\n" + "="*80)
    print("✅ Cumulative reward analysis complete!")
    print("="*80)
    print(f"\nOutputs:")
    print(f"  - Excel: {excel_output}")
    
    # Dynamically list enabled plots
    if PLOT_CONFIG['cumulative_rewards']['enabled']:
        print(f"  - Cumulative plot: {os.path.join(output_dir, 'cumulative_rewards.svg')}")
    if PLOT_CONFIG['episode_rewards']['enabled']:
        print(f"  - Episode rewards: {os.path.join(output_dir, 'episode_rewards.svg')}")
    if PLOT_CONFIG['episode_rewards_moving_avg']['enabled']:
        print(f"  - Moving average: {os.path.join(output_dir, 'episode_rewards_moving_avg.svg')}")
    
    print("\nValidation Summary:")
    print(f"  - Data verification: {'✅ PASSED' if verification_passed else '❌ FAILED'}")
    print(f"  - Accumulation check: {'✅ OK' if no_accumulation else '⚠️  WARNING'}")
    print("="*80)
    
    return verification_passed and no_accumulation


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
